apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "claims-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "claims-ui.name" . }}
    chart: {{ include "claims-ui.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "claims-ui.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "claims-ui.name" . }}
    spec:
      containers:
        - name: streamlit-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: password
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: API_ENDPOINT
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
